/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
    // Gives me all the build tasks
    id("java")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform {
		excludeTags("timing") // Exclude unit tests which I made strictly for timing purposes
	}
}

tasks.jar {
	isEnabled = false
}
tasks.processResources {
	isEnabled = false
}
tasks.processTestResources {
	isEnabled = false
}

// Compresses all openingBook files into one openingBook.zip
// Need to call this manually as gradle zip
tasks.register<Zip>("zip") {
    archiveFileName.set("openingBook.zip")
    destinationDirectory.set(layout.projectDirectory.dir("src/main/resources/"))

    from(layout.projectDirectory.dir("src/main/resources/openingBook"))
}

// Unzips all the Opening Book
tasks.register<Copy>("unzip") {
	from(zipTree("src/main/resources/openingBook.zip"))
    into(layout.projectDirectory.dir("src/main/resources/openingBook"))
}

// Now gradle build and test automatically call gradle unzip
tasks.build {
	dependsOn("unzip")
}
tasks.named<Test>("test") {
	dependsOn("unzip")
}
